# Generated by Django 5.1.3 on 2024-11-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alumno_envio_universidad_rename_profesor_docente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universidad',
            old_name='ubicacion',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='universidad',
            name='anio_fundacion',
        ),
    ]
